# pyproject.toml

[build-system]
requires = ["setuptools>=82.0.1"]
build-backend = "setuptools.build_meta"

[project]
name = "kha256"
version = "0.4.1"
dynamic = ["keywords", "maintainers"]
license = "AGPL-3.0-or-later"  # SPDX ID

# Diğer proje bilgileri (isteğe bağlı ama tavsiye edilir)
authors = [
    { name="Mehmet Keçeci", email="mkececi@yaani.com" },
]
description = "Keçeci Hash Algorithm (Keçeci Hash Algoritması), KHA-256"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Visualization",
]

# Ana bağımlılıklarınız
dependencies = [
    "numpy",
    "kececinumbers",
    "bcrypt",
    "blake3",
    "pycryptodome",
    "xxhash",
    "argon2-cffi",
    "pandas",
    "cryptography",
    "ipywidgets",
    "ipython",
    "scipy",
    "aiohttp",
    "python-dotenv",
    "nest-asyncio2",
]

[package.build-dependencies]
setuptools = ">=61.0"
cython = ">=3.0.0"
compilers = "*"  # Linux ortamında Cython kodunu derlemek için GCC/Clang kurar

[tool.pixi.package.build-dependencies]
setuptools = ">=61.0"
cython = ">=3.0.0"
compilers = "*"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]

[tool.setuptools.packages.find]
include = ["kha256*"]
exclude = ["binder", "build*", "content", "data", "dist", "dist*", "docs", "docs*", "examples*", "examples", "notebooks", "tests", "tests*"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["*.py", "*.pyi"]  # Sadece Python dosyaları

[project.urls]
Homepage = "https://github.com/WhiteSymmetry/kha256"
Repository = "https://github.com/WhiteSymmetry/kha256"

[dependency-groups]
build = [
    "setuptools (>=82.0.1)",
    "cython (>=3.2.5)"
]
