#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
KHA-256 Dokümantasyon Yeniden Oluşturucu
=========================================
Bu script, docs/ dizinini tamamen siler ve Sphinx ile sıfırdan
profesyonel bir dokümantasyon yapısı oluşturur.

Kullanım:
    python rebuild_docs.py
"""

import os
import sys
import shutil
import subprocess
from pathlib import Path

# ======================================================================
# YAPILANDIRMA
# ======================================================================

PROJECT_NAME = "KHA-256"
PROJECT_AUTHOR = "Mehmet Keçeci"
PROJECT_VERSION = "0.2.9"
PACKAGE_NAME = "kha256"  # Dokümantasyonu oluşturulacak paket

# Dosya yolları
ROOT_DIR = Path(__file__).parent.resolve()
DOCS_DIR = ROOT_DIR / "docs"
SOURCE_DIR = DOCS_DIR / "source"
API_DIR = SOURCE_DIR / "api"
PACKAGE_DIR = ROOT_DIR / PACKAGE_NAME

# ======================================================================
# YARDIMCI FONKSİYONLAR
# ======================================================================

def print_header(title: str) -> None:
    print(f"\n{'='*60}")
    print(f"  {title}")
    print('='*60)

def print_step(step: str) -> None:
    print(f"\n[→] {step}")

def run_command(cmd: list[str], cwd: Path | None = None) -> bool:
    """Komut çalıştır ve sonucu döndür."""
    try:
        result = subprocess.run(
            cmd,
            cwd=cwd,
            check=True,
            capture_output=True,
            text=True,
        )
        print(f"    ✓ Başarılı: {' '.join(cmd)}")
        return True
    except subprocess.CalledProcessError as e:
        print(f"    ✗ Hata: {e.stderr}")
        return False
    except FileNotFoundError:
        print(f"    ✗ Komut bulunamadı: {cmd[0]}")
        return False

# ======================================================================
# ANA İŞLEVLER
# ======================================================================

def clean_docs() -> None:
    """Mevcut docs/ dizinini tamamen sil."""
    print_step("Eski docs/ dizini siliniyor...")
    if DOCS_DIR.exists():
        shutil.rmtree(DOCS_DIR)
        print(f"    ✓ Silindi: {DOCS_DIR}")
    else:
        print(f"    ℹ Zaten yok: {DOCS_DIR}")

def create_structure() -> None:
    """Temel dizin yapısını oluştur."""
    print_step("Dizin yapısı oluşturuluyor...")
    SOURCE_DIR.mkdir(parents=True, exist_ok=True)
    API_DIR.mkdir(parents=True, exist_ok=True)
    (DOCS_DIR / "build").mkdir(parents=True, exist_ok=True)
    print(f"    ✓ {SOURCE_DIR}")
    print(f"    ✓ {API_DIR}")

def write_conf_py() -> None:
    """Modern ve tam yapılandırılmış conf.py oluştur."""
    print_step("conf.py oluşturuluyor...")
    
    conf_content = f'''# -*- coding: utf-8 -*-
"""
Sphinx configuration for {PROJECT_NAME} documentation.
Auto-generated by rebuild_docs.py
"""

import os
import sys
from datetime import datetime

# ======================================================================
# PATH CONFIGURATION
# ======================================================================
# Proje kök dizinini Python yoluna ekle
sys.path.insert(0, os.path.abspath('../..'))

# ======================================================================
# PROJECT INFORMATION
# ======================================================================
project = '{PROJECT_NAME}'
author = '{PROJECT_AUTHOR}'
copyright = f"{{datetime.now().year}}, {{author}}"
release = '{PROJECT_VERSION}'
version = '{PROJECT_VERSION}'

# ======================================================================
# EXTENSIONS
# ======================================================================
extensions = [
    'sphinx.ext.autodoc',           # Docstring'lerden otomatik dokümantasyon
    'sphinx.ext.autosummary',       # Özet tabloları
    'sphinx.ext.napoleon',          # Google/NumPy style docstring desteği
    'sphinx.ext.viewcode',          # Kaynak kod linkleri
    'sphinx.ext.intersphinx',       # Diğer projelere linkler
    'sphinx.ext.todo',              # Todo notları
    'sphinx.ext.coverage',          # Dokümantasyon kapsamı
    'sphinx.ext.mathjax',           # Matematiksel ifadeler
    'sphinx.ext.ifconfig',          # Koşullu içerik
    'sphinx.ext.githubpages',       # GitHub Pages desteği
]

# ======================================================================
# AUTODOC CONFIGURATION
# ======================================================================
autodoc_default_options = {{
    'members': True,
    'member-order': 'bysource',
    'undoc-members': True,
    'show-inheritance': True,
    'ignore-module-all': False,
}}
autodoc_typehints = 'description'
autodoc_typehints_format = 'short'
autosummary_generate = True

# ======================================================================
# NAPOLEON CONFIGURATION (Google/NumPy style docstrings)
# ======================================================================
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = True
napoleon_type_aliases = None
napoleon_attr_annotations = True

# ======================================================================
# TEMPLATES & SOURCE
# ======================================================================
templates_path = ['_templates']
source_suffix = {{
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}}
master_doc = 'index'
language = 'en'
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', '**.ipynb_checkpoints']
pygments_style = 'sphinx'
todo_include_todos = True

# ======================================================================
# HTML OUTPUT
# ======================================================================
html_theme = 'sphinx_rtd_theme'  # Read the Docs teması (pip install sphinx_rtd_theme)
html_theme_options = {{
    'navigation_depth': 4,
    'collapse_navigation': False,
    'sticky_navigation': True,
    'includehidden': True,
    'titles_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'logo_only': False,
}}
html_static_path = ['_static']
html_css_files = ['custom.css']
html_logo = 'logo.png' if os.path.exists('_static/logo.png') else None
html_favicon = None
html_show_sourcelink = True
html_show_sphinx = False
htmlhelp_basename = f'{{project}}doc'

# ======================================================================
# LATEX OUTPUT
# ======================================================================
latex_elements = {{}}
latex_documents = [
    (master_doc, f'{{project}}.tex', f'{{project}} Documentation', author, 'manual'),
]

# ======================================================================
# MAN PAGE OUTPUT
# ======================================================================
man_pages = [
    (master_doc, project.lower(), f'{{project}} Documentation', [author], 1),
]

# ======================================================================
# TEXINFO OUTPUT
# ======================================================================
texinfo_documents = [
    (master_doc, project, f'{{project}} Documentation', author, project,
     'A next-generation cryptographic hash algorithm.', 'Miscellaneous'),
]

# ======================================================================
# INTERSPHINX CONFIGURATION
# ======================================================================
intersphinx_mapping = {{
    'python': ('https://docs.python.org/3', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
}}
'''
    
    conf_path = SOURCE_DIR / "conf.py"
    conf_path.write_text(conf_content, encoding='utf-8')
    print(f"    ✓ Oluşturuldu: {conf_path}")

def write_index_rst() -> None:
    """Profesyonel index.rst şablonu oluştur."""
    print_step("index.rst oluşturuluyor...")
    
    index_content = f""".. {PROJECT_NAME} documentation master file

{'='*len(PROJECT_NAME)}
{PROJECT_NAME} Documentation
{'='*len(PROJECT_NAME)}

.. image:: _static/logo.png
   :alt: {PROJECT_NAME} Logo
   :width: 200px
   :align: center

**Performance-Sacrificed, Security-Maximized Hash Algorithm**

.. toctree::
   :maxdepth: 2
   :caption: Contents
   
   quickstart
   installation
   usage

.. toctree::
   :maxdepth: 3
   :caption: API Reference
   
   api/modules

.. toctree::
   :maxdepth: 2
   :caption: Additional Resources
   
   citation
   changelog

Overview
========

{PROJECT_NAME} is a 256-bit cryptographic hash function designed with **security 
prioritized over performance**. It employs advanced mathematical foundations 
from Keçeci Numbers and provides quantum-resistant features.

Key Features
------------

* **256-bit hash output** (64-character hexadecimal)
* **Strong avalanche effect** (>49.5% in ideal range)
* **Quantum-resistant design** with post-quantum mixing
* **Multiple Keçeci Number types** (22 different mathematical systems)
* **Entropy injection** from time and system sources
* **Double hashing** for additional security layer
* **Configurable security parameters**

Quick Example
-------------

.. code-block:: python

   from {PACKAGE_NAME} import quick_hash
   
   result = quick_hash("Hello {PROJECT_NAME}!")
   print(f"Hash: {{result}}")

Indices and Tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
"""
    
    index_path = SOURCE_DIR / "index.rst"
    index_path.write_text(index_content, encoding='utf-8')
    print(f"    ✓ Oluşturuldu: {index_path}")

def generate_api_docs() -> bool:
    """sphinx-apidoc ile API dokümantasyonu oluştur."""
    print_step("API dokümantasyonu oluşturuluyor (sphinx-apidoc)...")
    
    if not PACKAGE_DIR.exists():
        print(f"    ✗ Paket dizini bulunamadı: {PACKAGE_DIR}")
        return False
    
    cmd = [
        'sphinx-apidoc',
        '--force',              # Mevcut dosyaların üzerine yaz
        '--separate',           # Her modül için ayrı dosya
        '--module-first',       # Modül dokümantasyonunu en üste koy
        '--no-toc',             # TOC dosyası oluşturma
        '--output-dir', str(API_DIR),
        str(PACKAGE_DIR),
    ]
    
    return run_command(cmd)

def write_placeholder_files() -> None:
    """Eksik .rst dosyaları için placeholder oluştur."""
    print_step("Placeholder dosyaları oluşturuluyor...")
    
    placeholders = {
        'quickstart.rst': """Quickstart
==========

.. TODO: Add quickstart guide here

Coming soon...
""",
        'installation.rst': """Installation
============

.. TODO: Add installation guide here

Via pip:

.. code-block:: bash

   pip install kha256
""",
        'usage.rst': """Usage
=====

.. TODO: Add usage examples here

Basic Usage
-----------

.. code-block:: python

   from kha256 import quick_hash
   
   result = quick_hash("Hello World!")
   print(result)
""",
        'citation.rst': """Citation
========

If you use KHA-256 in your research, please cite:

.. code-block:: bibtex

   @misc{kececi_2026_18156885,
     author = {Keçeci, Mehmet},
     title  = {KHA-256: A Next-Generation Cryptographic Hash Function},
     year   = {2026},
     doi    = {10.5281/zenodo.18156885},
   }
""",
        'changelog.rst': """Changelog
=========

v0.2.9 (2026-01-XX)
-------------------

* Initial release
* Security-maximized implementation
* 22 Keçeci Number types support
""",
    }
    
    for filename, content in placeholders.items():
        path = SOURCE_DIR / filename
        if not path.exists():
            path.write_text(content, encoding='utf-8')
            print(f"    ✓ Oluşturuldu: {filename}")

def write_gitignore() -> None:
    """docs/.gitignore oluştur."""
    print_step(".gitignore oluşturuluyor...")
    
    gitignore_content = """# Sphinx build output
_build/
build/

# Python
__pycache__/
*.py[cod]
*$py.class
*.so

# Sphinx extensions
.autosummary/
.doctrees/

# Jupyter Notebook
.ipynb_checkpoints/

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
"""
    
    gitignore_path = DOCS_DIR / ".gitignore"
    gitignore_path.write_text(gitignore_content, encoding='utf-8')
    print(f"    ✓ Oluşturuldu: {gitignore_path}")

def write_makefile() -> None:
    """docs/Makefile oluştur."""
    print_step("Makefile oluşturuluyor...")
    
    makefile_content = """# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line, and also
# from the environment for the first two.
SPHINXOPTS    ?=
SPHINXBUILD   ?= sphinx-build
SOURCEDIR     = source
BUILDDIR      = build

# Put it first so that "make" without argument is like "make help".
help:
\t@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

# Regenerate API docs before building
apidoc:
\t@sphinx-apidoc --force --separate --module-first --no-toc \\
\t\t-o source/api ../kha256/

# Build HTML with fresh API docs
html: apidoc
\t@$(SPHINXBUILD) -M html "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

# Clean everything
clean:
\trm -rf $(BUILDDIR)/*
\trm -rf source/api/*

.PHONY: help Makefile apidoc html clean

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
\t@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
"""
    
    makefile_path = DOCS_DIR / "Makefile"
    makefile_path.write_text(makefile_content, encoding='utf-8')
    print(f"    ✓ Oluşturuldu: {makefile_path}")

def write_make_bat() -> None:
    """Windows için make.bat oluştur."""
    print_step("make.bat oluşturuluyor (Windows)...")
    
    bat_content = """@ECHO OFF

pushd %~dp0

REM Command file for Sphinx documentation

if "%SPHINXBUILD%" == "" (
\tset SPHINXBUILD=sphinx-build
)
set SOURCEDIR=source
set BUILDDIR=build

%SPHINXBUILD% >NUL 2>NUL
if errorlevel 9009 (
\techo.
\techo.The 'sphinx-build' command was not found. Make sure you have Sphinx
\techo.installed, then set the SPHINXBUILD environment variable to point
\techo.to the full path of the 'sphinx-build' executable. Alternatively you
\techo.may add the Sphinx directory to PATH.
\techo.
\techo.If you don't have Sphinx installed, grab it from
\techo.https://www.sphinx-doc.org/
\texit /b 1
)

if "%1" == "" goto help
if "%1" == "apidoc" goto apidoc
if "%1" == "clean" goto clean

%SPHINXBUILD% -M %1 %SOURCEDIR% %BUILDDIR% %SPHINXOPTS% %O%
goto end

:apidoc
sphinx-apidoc --force --separate --module-first --no-toc -o source/api ../kha256/
goto end

:clean
rmdir /s /q %BUILDDIR% 2>NUL
rmdir /s /q source\\api 2>NUL
mkdir source\\api
goto end

:help
%SPHINXBUILD% -M help %SOURCEDIR% %BUILDDIR% %SPHINXOPTS% %O%

:end
popd
"""
    
    bat_path = DOCS_DIR / "make.bat"
    bat_path.write_text(bat_content, encoding='utf-8')
    print(f"    ✓ Oluşturuldu: {bat_path}")

def check_dependencies() -> bool:
    """Gerekli bağımlılıkları kontrol et."""
    print_step("Bağımlılıklar kontrol ediliyor...")
    
    required = ['sphinx', 'sphinx_rtd_theme']
    missing = []
    
    for pkg in required:
        try:
            __import__(pkg)
            print(f"    ✓ {pkg}")
        except ImportError:
            print(f"    ✗ {pkg} (eksik)")
            missing.append(pkg)
    
    if missing:
        print(f"\n⚠ Eksik paketler: {', '.join(missing)}")
        print("  Kurulum için:")
        print(f"  pip install {' '.join(missing)}")
        return False
    
    return True

# ======================================================================
# MAIN
# ======================================================================

def main() -> int:
    print_header(f"{PROJECT_NAME} Dokümantasyon Yeniden Oluşturucu")
    
    # 1. Bağımlılıkları kontrol et
    if not check_dependencies():
        return 1
    
    # 2. Eski docs'ı sil
    clean_docs()
    
    # 3. Dizin yapısını oluştur
    create_structure()
    
    # 4. conf.py oluştur
    write_conf_py()
    
    # 5. index.rst oluştur
    write_index_rst()
    
    # 6. Placeholder dosyaları oluştur
    write_placeholder_files()
    
    # 7. API dokümantasyonu oluştur
    if not generate_api_docs():
        print("\n⚠ API dokümantasyonu oluşturulamadı. Paket yolunu kontrol edin.")
    
    # 8. Makefile ve make.bat oluştur
    write_makefile()
    write_make_bat()
    
    # 9. .gitignore oluştur
    write_gitignore()
    
    # 10. Özet
    print_header("✅ TAMAMLANDI")
    print(f"""
Dokümantasyon başarıyla oluşturuldu:
  📁 {DOCS_DIR}

Sonraki Adımlar:
  1. Dokümantasyonu derle:
     cd docs && make html

  2. Tarayıcıda aç:
     xdg-open build/html/index.html  (Linux)
     open build/html/index.html      (macOS)
     start build\\html\\index.html     (Windows)

  3. Read the Docs'a yükle:
     - docs/ klasörünü Git'e commit et
     - readthedocs.org'da projeyi bağla

Oluşturulan Dosyalar:
  • docs/source/conf.py         (Sphinx yapılandırması)
  • docs/source/index.rst       (Ana sayfa)
  • docs/source/api/            (API referansları)
  • docs/Makefile               (Linux/macOS derleme)
  • docs/make.bat               (Windows derleme)
  • docs/.gitignore             (Git için)
""")
    
    return 0

if __name__ == '__main__':
    sys.exit(main())
