# latexmkrc

# LATEXOPTS tanımlı mı kontrol et, değilse boş string yap
my $latexopts = $ENV{'LATEXOPTS'} // '';

$latex = 'latex ' . $latexopts . ' %O %S';
$pdflatex = 'pdflatex ' . $latexopts . ' %O %S';
$lualatex = 'lualatex ' . $latexopts . ' %O %S';
$xelatex = 'xelatex --no-pdf ' . $latexopts . ' %O %S';

$makeindex = 'makeindex -s python.ist %O -o %D %S';
add_cus_dep( "glo", "gls", 0, "makeglo" );
sub makeglo {
    return system( "makeindex -s gglo.ist -o '$_[0].gls' '$_[0].glo'" );
}
