name: kha256-jupyterbook
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - matplotlib
  - scipy
  - jupyterlab
  - nodejs
  - jupyter-book
  - myst-nb
  - sphinx-book-theme
  - pip:
    - kececinumbers
    - kha256
    - ipywidgets
    - plotly
    - seaborn
    - sphinx
    - sphinx-autobuild
