name: Run tests and upload coverage-Codecov

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install -y pytest pytest-cov
          # packageName'unuzu local package'i kurun
          pip install -e .

      - name: Run tests
        run: pytest --cov --cov-branch --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: WhiteSymmetry/kha256
